import { FactoryOverview, AssetTelemetry, ZoneSummary, AlertItem, WorkOrder, AIPrescriptionItem, AIModelMetrics } from "./types";

export const MOCK_ZONES: ZoneSummary[] = [
  {
    id: "production",
    name: "Production & Machining Lines",
    description: "High-precision CNC 5-axis milling centers, automated hydraulic stamping presses, and robotic assembly cells.",
    supervisor: "[OP-01]",
    total_assets: 4,
    healthy_assets: 2,
    warning_assets: 1,
    critical_assets: 1,
    health_score: 72.4,
    oee: 86.8,
    availability: 89.2,
    performance: 97.5,
    quality: 99.1,
    active_alarms_count: 2,
    downtime_hrs_24h: 2.2,
    downtime_cost_24h_usd: 28700.0,
    power_consumption_kwh: 345.0,
    status: "Critical",
    schematic_type: "production_cell_layout"
  },
  {
    id: "packaging",
    name: "Packaging & Bottling Line",
    description: "High-speed horizontal flow wrapping, automated carton formers, and robotic palletizing cells.",
    supervisor: "[OP-02]",
    total_assets: 3,
    healthy_assets: 2,
    warning_assets: 1,
    critical_assets: 0,
    health_score: 86.5,
    oee: 92.4,
    availability: 95.0,
    performance: 98.2,
    quality: 99.0,
    active_alarms_count: 1,
    downtime_hrs_24h: 0.4,
    downtime_cost_24h_usd: 4200.0,
    power_consumption_kwh: 120.0,
    status: "Warning",
    schematic_type: "packaging_conveyor_layout"
  },
  {
    id: "warehouse",
    name: "Warehouse & Logistics (AS/RS)",
    description: "Automated High-Bay Storage and Retrieval Systems (AS/RS), automated sorting diverters, and AGV fleet.",
    supervisor: "[OP-03]",
    total_assets: 4,
    healthy_assets: 3,
    warning_assets: 1,
    critical_assets: 0,
    health_score: 89.0,
    oee: 94.2,
    availability: 96.5,
    performance: 98.4,
    quality: 99.2,
    active_alarms_count: 1,
    downtime_hrs_24h: 0.4,
    downtime_cost_24h_usd: 4200.0,
    power_consumption_kwh: 180.0,
    status: "Warning",
    schematic_type: "asrs_racking_layout"
  },
  {
    id: "utilities",
    name: "Utilities, Power & Plant HVAC",
    description: "Heavy industrial centrifugal air compressors, 500TR water chillers, steam boilers, and high-voltage substations.",
    supervisor: "[ENG-04]",
    total_assets: 5,
    healthy_assets: 3,
    warning_assets: 1,
    critical_assets: 1,
    health_score: 76.5,
    oee: 91.2,
    availability: 94.5,
    performance: 97.0,
    quality: 99.5,
    active_alarms_count: 2,
    downtime_hrs_24h: 2.2,
    downtime_cost_24h_usd: 28700.0,
    power_consumption_kwh: 1850.0,
    status: "Critical",
    schematic_type: "utilities_scada_layout"
  },
  {
    id: "quality",
    name: "Quality Assurance & Metrology",
    description: "Automated AI vision inspection gantries, high-precision laser micrometers, and ultrasonic NDT scanners.",
    supervisor: "[QA-05]",
    total_assets: 2,
    healthy_assets: 2,
    warning_assets: 0,
    critical_assets: 0,
    health_score: 98.0,
    oee: 98.4,
    availability: 99.5,
    performance: 99.2,
    quality: 99.7,
    active_alarms_count: 0,
    downtime_hrs_24h: 0.0,
    downtime_cost_24h_usd: 0.0,
    power_consumption_kwh: 18.0,
    status: "Healthy",
    schematic_type: "qa_inspection_layout"
  }
];

export const MOCK_ASSETS: AssetTelemetry[] = [
  {
    id: "cmp-01",
    name: "Centrifugal Air Compressor 01 (250kW)",
    zone_id: "utilities",
    zone_name: "Utilities, Power & Plant HVAC",
    category: "compressor",
    status: "Critical",
    health_state: "Critical",
    operational_hours: 4820.5,
    oee: 74.8,
    availability: 78.5,
    performance: 96.0,
    quality: 99.2,
    load_pct: 86.4,
    rpm: 2985.0,
    power_kw: 246.8,
    vibration_x: 3.42,
    vibration_y: 2.91,
    vibration_z: 2.40,
    vibration_peak: 6.84,
    vibration_crest_factor: 2.0,
    temperature_motor: 88.5,
    temperature_bearing: 94.2,
    temperature_ambient: 24.1,
    motor_current_a: 154.2,
    phase_imbalance_pct: 2.85,
    acoustic_emission_db: 74.5,
    pressure_bar: 6.85,
    pressure_diff_bar: 0.82,
    flow_rate_lpm: 38.4,
    oil_iso_code: "22/19/16",
    oil_particles_count: 1420,
    tank_level_pct: 68.5,
    air_quality_voc_ppm: 0.14,
    prediction: {
      rul_cycles: 28,
      rul_hours: 67.2,
      rul_ci_lower: 22.5,
      rul_ci_upper: 34.0,
      health_index: 38.5,
      health_state: "Critical",
      failure_mode: "Bearing Outer Race Defect",
      failure_mode_probability: 88.4,
      failure_mode_distribution: {
        "Bearing Outer Race Defect": 0.884,
        "Stator Winding Overheat": 0.062,
        "Shaft Misalignment & Looseness": 0.038,
        "Cavitation & Seal Degradation": 0.012,
        "Spindle Tool Wear": 0.002,
        "Pneumatic Valve Leak & Pressure Loss": 0.002
      },
      anomaly_score: 0.945,
      lead_time_hours: 43.7,
      shap_contributions: {
        "Triaxial Vibration RMS": 42.5,
        "Bearing Temperature RTD": 31.8,
        "Acoustic Ultrasound": 14.2,
        "Motor Current (MCSA)": 6.5,
        "Differential Pressure": 3.0,
        "Oil Particle Index (ISO)": 2.0
      },
      prescriptive_action: "1. Lockout/Tagout asset. 2. Decouple motor. 3. Extract worn drive-end bearing using hydraulic puller. 4. Heat replacement SKF 6314-2Z/C3 bearing (110°C) and press onto shaft. 5. Pack with 40g Klüberquiet grease. 6. Laser align shaft within 0.03mm tolerance.",
      estimated_wrench_time_hrs: 3.5,
      required_parts: ["SKF Explorer 6314-2Z/C3 Deep Groove Bearing", "Klüberquiet BQ 72-72 Synthetic Grease", "Viton Dual Lip Shaft Seal 70x90x10"],
      downtime_cost_risk_usd: 54000.0
    },
    components: [
      { id: "cmp01-motor", name: "3-Phase Induction Motor (250kW)", component_type: "motor", health_score: 48.0, status: "Warning", temperature: 88.5, vibration_rms: 2.91, failure_risk: 0.52, defect_type: "Stator Overheat", hotspot: true },
      { id: "cmp01-drive-brg", name: "Drive-End Spherical Roller Bearing", component_type: "bearing", health_score: 24.5, status: "Critical", temperature: 94.2, vibration_rms: 3.93, failure_risk: 0.76, defect_type: "Bearing Outer Race Defect", hotspot: true },
      { id: "cmp01-volute", name: "Cast Steel Volute & High-Pressure Casing", component_type: "impeller", health_score: 62.0, status: "Warning", temperature: 80.5, vibration_rms: 2.40, failure_risk: 0.38, defect_type: "Cavitation Wear", hotspot: true },
      { id: "cmp01-shaft", name: "Forged Alloy Main Drive Shaft & Coupling", component_type: "shaft", health_score: 55.0, status: "Warning", temperature: 83.5, vibration_rms: 2.74, failure_risk: 0.45, defect_type: null, hotspot: false },
      { id: "cmp01-valves", name: "Electro-Pneumatic Unloader Valve Block", component_type: "valve", health_score: 62.2, status: "Warning", temperature: 36.1, vibration_rms: 1.37, failure_risk: 0.38, defect_type: "Pneumatic Micro-Leak", hotspot: true }
    ],
    last_updated: "2026-08-27 17:45:00"
  },
  {
    id: "cnc-01",
    name: "5-Axis CNC Milling Center 01 (DMG Mori)",
    zone_id: "production",
    zone_name: "Production & Machining Lines",
    category: "cnc_mill",
    status: "Critical",
    health_state: "Critical",
    operational_hours: 3120.0,
    oee: 78.2,
    availability: 82.0,
    performance: 96.5,
    quality: 98.8,
    load_pct: 91.2,
    rpm: 18020.0,
    power_kw: 44.5,
    vibration_x: 2.85,
    vibration_y: 2.42,
    vibration_z: 1.98,
    vibration_peak: 5.70,
    vibration_crest_factor: 2.0,
    temperature_motor: 78.0,
    temperature_bearing: 86.5,
    temperature_ambient: 23.5,
    motor_current_a: 68.2,
    phase_imbalance_pct: 1.95,
    acoustic_emission_db: 68.0,
    pressure_bar: 20.5,
    pressure_diff_bar: 0.65,
    flow_rate_lpm: 18.2,
    oil_iso_code: "20/18/15",
    oil_particles_count: 980,
    tank_level_pct: 74.0,
    air_quality_voc_ppm: 0.11,
    prediction: {
      rul_cycles: 42,
      rul_hours: 100.8,
      rul_ci_lower: 35.0,
      rul_ci_upper: 49.0,
      health_index: 44.0,
      health_state: "Critical",
      failure_mode: "Spindle Tool Wear",
      failure_mode_probability: 82.5,
      failure_mode_distribution: {
        "Spindle Tool Wear": 0.825,
        "Bearing Outer Race Defect": 0.115,
        "Shaft Misalignment & Looseness": 0.045,
        "Stator Winding Overheat": 0.015
      },
      anomaly_score: 0.890,
      lead_time_hours: 65.5,
      shap_contributions: {
        "Triaxial Vibration RMS": 38.0,
        "Oil Particle Index (ISO)": 28.5,
        "Bearing Temperature RTD": 19.5,
        "Acoustic Ultrasound": 9.0,
        "Motor Current (MCSA)": 5.0
      },
      prescriptive_action: "1. Halt CNC program. 2. Measure tool runout. 3. Index worn carbide inserts. 4. Inspect ceramic hybrid spindle bearings. 5. Verify through-spindle coolant flow (>18 L/min at 20 bar).",
      estimated_wrench_time_hrs: 1.5,
      required_parts: ["Ceramic Hybrid Spindle Bearing Set H7008C", "BT40 Tool Holder Pull Studs"],
      downtime_cost_risk_usd: 38000.0
    },
    components: [
      { id: "cnc01-spindle", name: "High-Speed Electro-Spindle (20,000 RPM)", component_type: "spindle", health_score: 36.0, status: "Critical", temperature: 86.5, vibration_rms: 3.28, failure_risk: 0.64, defect_type: "Spindle Tool Wear", hotspot: true },
      { id: "cnc01-bearing", name: "Ceramic Hybrid Angular Contact Bearings", component_type: "bearing", health_score: 41.0, status: "Warning", temperature: 84.0, vibration_rms: 2.85, failure_risk: 0.59, defect_type: null, hotspot: false },
      { id: "cnc01-tooling", name: "Automatic Tool Changer (40-Pocket BT40)", component_type: "gearbox", health_score: 72.0, status: "Warning", temperature: 48.0, vibration_rms: 1.20, failure_risk: 0.28, defect_type: null, hotspot: false }
    ],
    last_updated: "2026-08-27 17:45:00"
  },
  {
    id: "wrp-01",
    name: "High-Speed Flow Packaging Wrapper",
    zone_id: "packaging",
    zone_name: "Packaging & Bottling Line",
    category: "flow_wrapper",
    status: "Degraded",
    health_state: "Warning",
    operational_hours: 2840.0,
    oee: 88.5,
    availability: 92.0,
    performance: 97.0,
    quality: 99.2,
    load_pct: 79.5,
    rpm: 320.0,
    power_kw: 28.4,
    vibration_x: 1.65,
    vibration_y: 1.40,
    vibration_z: 1.15,
    vibration_peak: 3.30,
    vibration_crest_factor: 2.0,
    temperature_motor: 64.0,
    temperature_bearing: 72.0,
    temperature_ambient: 23.0,
    motor_current_a: 38.5,
    phase_imbalance_pct: 1.10,
    acoustic_emission_db: 48.0,
    pressure_bar: 5.8,
    pressure_diff_bar: 0.35,
    flow_rate_lpm: 12.0,
    oil_iso_code: "18/16/13",
    oil_particles_count: 520,
    tank_level_pct: 82.0,
    air_quality_voc_ppm: 0.08,
    prediction: {
      rul_cycles: 95,
      rul_hours: 228.0,
      rul_ci_lower: 82.0,
      rul_ci_upper: 108.0,
      health_index: 68.0,
      health_state: "Warning",
      failure_mode: "Pneumatic Valve Leak & Pressure Loss",
      failure_mode_probability: 72.0,
      failure_mode_distribution: {
        "Pneumatic Valve Leak & Pressure Loss": 0.720,
        "Bearing Outer Race Defect": 0.180,
        "Stator Winding Overheat": 0.100
      },
      anomaly_score: 0.450,
      lead_time_hours: 148.0,
      shap_contributions: {
        "Differential Pressure": 45.0,
        "Acoustic Ultrasound": 28.0,
        "Triaxial Vibration RMS": 17.0,
        "Motor Current (MCSA)": 10.0
      },
      prescriptive_action: "1. Depressurize pneumatic manifold. 2. Ultrasonic scan along pilot lines. 3. Replace cracked 12mm tubing. 4. Swap worn solenoid valve spool seal.",
      estimated_wrench_time_hrs: 2.0,
      required_parts: ["Festo 5/2 Directional Solenoid Valve", "Polyurethane 12mm Pneumatic Tubing"],
      downtime_cost_risk_usd: 14500.0
    },
    components: [
      { id: "wrp01-motor", name: "Synchronous Servo Infeed Drive Motor", component_type: "motor", health_score: 72.0, status: "Warning", temperature: 64.0, vibration_rms: 1.40, failure_risk: 0.28, defect_type: null, hotspot: false },
      { id: "wrp01-seal", name: "Rotary Heat Sealer", component_type: "valve", health_score: 61.0, status: "Warning", temperature: 148.0, vibration_rms: 0.65, failure_risk: 0.39, defect_type: "Pneumatic Micro-Leak", hotspot: true },
      { id: "wrp01-knife", name: "Rotary Cutting Anvil", component_type: "spindle", health_score: 74.0, status: "Warning", temperature: 55.0, vibration_rms: 1.65, failure_risk: 0.26, defect_type: null, hotspot: false }
    ],
    last_updated: "2026-08-27 17:45:00"
  },
  {
    id: "asrs-01",
    name: "Automated High-Bay Stacker Crane 01",
    zone_id: "warehouse",
    zone_name: "Warehouse & Logistics (AS/RS)",
    category: "asrs_crane",
    status: "Degraded",
    health_state: "Warning",
    operational_hours: 5120.0,
    oee: 89.4,
    availability: 93.5,
    performance: 96.5,
    quality: 99.0,
    load_pct: 82.0,
    rpm: 1445.0,
    power_kw: 76.5,
    vibration_x: 1.85,
    vibration_y: 1.55,
    vibration_z: 1.30,
    vibration_peak: 3.70,
    vibration_crest_factor: 2.0,
    temperature_motor: 62.0,
    temperature_bearing: 70.5,
    temperature_ambient: 21.0,
    motor_current_a: 92.5,
    phase_imbalance_pct: 1.45,
    acoustic_emission_db: 52.0,
    pressure_bar: 0.0,
    pressure_diff_bar: 0.0,
    flow_rate_lpm: 0.0,
    oil_iso_code: "18/16/13",
    oil_particles_count: 580,
    tank_level_pct: 88.0,
    air_quality_voc_ppm: 0.04,
    prediction: {
      rul_cycles: 110,
      rul_hours: 264.0,
      rul_ci_lower: 96.0,
      rul_ci_upper: 125.0,
      health_index: 64.5,
      health_state: "Warning",
      failure_mode: "Shaft Misalignment & Looseness",
      failure_mode_probability: 74.5,
      failure_mode_distribution: {
        "Shaft Misalignment & Looseness": 0.745,
        "Bearing Outer Race Defect": 0.185,
        "Stator Winding Overheat": 0.070
      },
      anomaly_score: 0.480,
      lead_time_hours: 171.6,
      shap_contributions: {
        "Triaxial Vibration RMS": 48.0,
        "Motor Current (MCSA)": 26.0,
        "Bearing Temperature RTD": 16.0,
        "Acoustic Ultrasound": 10.0
      },
      prescriptive_action: "1. Secure coupling lock. 2. Mount laser alignment heads. 3. Check soft foot (<0.05mm). 4. Adjust elevation with stainless shims. 5. Torque foundation bolts to 185 Nm.",
      estimated_wrench_time_hrs: 2.5,
      required_parts: ["Stainless Steel Pre-Cut Alignment Shims (0.05-2mm)", "Lovejoy Jaw Coupling Elastomer Insert"],
      downtime_cost_risk_usd: 18500.0
    },
    components: [
      { id: "asrs01-travel", name: "Travel Gearmotor & Brake", component_type: "gearbox", health_score: 62.0, status: "Warning", temperature: 70.5, vibration_rms: 1.85, failure_risk: 0.38, defect_type: "Shaft Misalignment", hotspot: true },
      { id: "asrs01-hoist", name: "Twin Cable Hoist Drum", component_type: "belt", health_score: 75.0, status: "Healthy", temperature: 55.0, vibration_rms: 1.10, failure_risk: 0.25, defect_type: null, hotspot: false },
      { id: "asrs01-fork", name: "Telescopic Deep-Lane Forks", component_type: "shaft", health_score: 82.0, status: "Healthy", temperature: 38.0, vibration_rms: 0.85, failure_risk: 0.18, defect_type: null, hotspot: false }
    ],
    last_updated: "2026-08-27 17:45:00"
  },
  {
    id: "chl-01",
    name: "Industrial Chilled Water Chiller (500 TR)",
    zone_id: "utilities",
    zone_name: "Utilities, Power & Plant HVAC",
    category: "chiller",
    status: "Operational",
    health_state: "Healthy",
    operational_hours: 6420.0,
    oee: 95.8,
    availability: 98.2,
    performance: 98.0,
    quality: 99.6,
    load_pct: 72.0,
    rpm: 1785.0,
    power_kw: 378.0,
    vibration_x: 0.58,
    vibration_y: 0.48,
    vibration_z: 0.40,
    vibration_peak: 1.16,
    vibration_crest_factor: 2.0,
    temperature_motor: 52.0,
    temperature_bearing: 58.0,
    temperature_ambient: 23.5,
    motor_current_a: 212.0,
    phase_imbalance_pct: 0.65,
    acoustic_emission_db: 42.0,
    pressure_bar: 4.8,
    pressure_diff_bar: 0.25,
    flow_rate_lpm: 85.0,
    oil_iso_code: "16/14/11",
    oil_particles_count: 240,
    tank_level_pct: 91.0,
    air_quality_voc_ppm: 0.05,
    prediction: {
      rul_cycles: 245,
      rul_hours: 588.0,
      rul_ci_lower: 215.0,
      rul_ci_upper: 280.0,
      health_index: 91.5,
      health_state: "Healthy",
      failure_mode: "Bearing Outer Race Defect",
      failure_mode_probability: 32.0,
      failure_mode_distribution: {
        "Bearing Outer Race Defect": 0.320,
        "Cavitation & Seal Degradation": 0.280,
        "Stator Winding Overheat": 0.200,
        "Shaft Misalignment & Looseness": 0.200
      },
      anomaly_score: 0.085,
      lead_time_hours: 382.2,
      shap_contributions: {
        "Triaxial Vibration RMS": 22.0,
        "Bearing Temperature RTD": 20.0,
        "Motor Current (MCSA)": 18.0,
        "Acoustic Ultrasound": 15.0,
        "Differential Pressure": 15.0,
        "Oil Particle Index (ISO)": 10.0
      },
      prescriptive_action: "Asset operating within nominal OEM tolerances. Perform routine monthly lubrication check.",
      estimated_wrench_time_hrs: 0.5,
      required_parts: ["Synthetic Refrigeration Compressor Oil POE 68"],
      downtime_cost_risk_usd: 1200.0
    },
    components: [
      { id: "chl01-comp", name: "Semi-Hermetic Screw Compressor", component_type: "motor", health_score: 92.0, status: "Healthy", temperature: 58.0, vibration_rms: 0.58, failure_risk: 0.08, defect_type: null, hotspot: false },
      { id: "chl01-evap", name: "Shell & Tube Evaporator", component_type: "valve", health_score: 94.0, status: "Healthy", temperature: 6.2, vibration_rms: 0.22, failure_risk: 0.06, defect_type: null, hotspot: false },
      { id: "chl01-cond", name: "Water-Cooled Condenser Unit", component_type: "impeller", health_score: 90.0, status: "Healthy", temperature: 32.0, vibration_rms: 0.45, failure_risk: 0.10, defect_type: null, hotspot: false }
    ],
    last_updated: "2026-08-27 17:45:00"
  },
  {
    id: "rob-01",
    name: "6-Axis Heavy Robotic Assembly Cell",
    zone_id: "production",
    zone_name: "Production & Machining Lines",
    category: "robotic_arm",
    status: "Operational",
    health_state: "Healthy",
    operational_hours: 4120.0,
    oee: 96.2,
    availability: 98.5,
    performance: 98.0,
    quality: 99.7,
    load_pct: 68.0,
    rpm: 60.0,
    power_kw: 28.5,
    vibration_x: 0.32,
    vibration_y: 0.28,
    vibration_z: 0.24,
    vibration_peak: 0.64,
    vibration_crest_factor: 2.0,
    temperature_motor: 46.0,
    temperature_bearing: 51.0,
    temperature_ambient: 22.0,
    motor_current_a: 26.5,
    phase_imbalance_pct: 0.55,
    acoustic_emission_db: 30.0,
    pressure_bar: 6.2,
    pressure_diff_bar: 0.15,
    flow_rate_lpm: 0.0,
    oil_iso_code: "15/13/10",
    oil_particles_count: 180,
    tank_level_pct: 95.0,
    air_quality_voc_ppm: 0.03,
    prediction: {
      rul_cycles: 320,
      rul_hours: 768.0,
      rul_ci_lower: 285.0,
      rul_ci_upper: 360.0,
      health_index: 94.0,
      health_state: "Healthy",
      failure_mode: "Shaft Misalignment & Looseness",
      failure_mode_probability: 25.0,
      failure_mode_distribution: {
        "Shaft Misalignment & Looseness": 0.250,
        "Bearing Outer Race Defect": 0.250,
        "Stator Winding Overheat": 0.250,
        "Pneumatic Valve Leak & Pressure Loss": 0.250
      },
      anomaly_score: 0.060,
      lead_time_hours: 499.2,
      shap_contributions: {
        "Triaxial Vibration RMS": 25.0,
        "Bearing Temperature RTD": 25.0,
        "Motor Current (MCSA)": 25.0,
        "Acoustic Ultrasound": 25.0
      },
      prescriptive_action: "Robotic cell operating within precision tolerances. Baseline kinematics nominal.",
      estimated_wrench_time_hrs: 0.5,
      required_parts: ["Harmonic Drive Grease Cartridge 4B No.2"],
      downtime_cost_risk_usd: 800.0
    },
    components: [
      { id: "rob01-j1", name: "Base & Waist Harmonic Drive Gearbox J1", component_type: "gearbox", health_score: 95.0, status: "Healthy", temperature: 48.0, vibration_rms: 0.32, failure_risk: 0.05, defect_type: null, hotspot: false },
      { id: "rob01-j2", name: "Shoulder Articulation Servo Actuator J2", component_type: "motor", health_score: 94.0, status: "Healthy", temperature: 51.0, vibration_rms: 0.28, failure_risk: 0.06, defect_type: null, hotspot: false },
      { id: "rob01-j3", name: "Elbow Flex Pivot Joint J3", component_type: "motor", health_score: 93.0, status: "Healthy", temperature: 47.0, vibration_rms: 0.25, failure_risk: 0.07, defect_type: null, hotspot: false },
      { id: "rob01-wrist", name: "3-Axis Precision Wrist & End-Effector", component_type: "gearbox", health_score: 96.0, status: "Healthy", temperature: 38.0, vibration_rms: 0.20, failure_risk: 0.04, defect_type: null, hotspot: false }
    ],
    last_updated: "2026-08-27 17:45:00"
  }
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "ALT-CMP01-1042",
    asset_id: "cmp-01",
    asset_name: "Centrifugal Air Compressor 01 (250kW)",
    zone_id: "utilities",
    zone_name: "Utilities, Power & Plant HVAC",
    timestamp: "2026-08-27 17:42:15",
    severity: "CRITICAL",
    title: "CMP-01 Bearing Outer Race Defect Predicted",
    description: "AI anomaly confidence 88%. RUL countdown estimated at 28 cycles (67.2h). Lead time window: 43.7h.",
    failure_mode: "Bearing Outer Race Defect",
    sensor_trigger: "Triaxial Vibration Accelerometer (X-Axis)",
    trigger_value: "3.42 mm/s",
    threshold_value: "2.80 mm/s (Warn) / 4.50 mm/s (Crit)",
    lead_time_hours: 43.7,
    estimated_cost_usd: 54000.0,
    acknowledged: false,
    work_order_id: "WO-8921"
  },
  {
    id: "ALT-CNC01-1038",
    asset_id: "cnc-01",
    asset_name: "5-Axis CNC Milling Center 01 (DMG Mori)",
    zone_id: "production",
    zone_name: "Production & Machining Lines",
    timestamp: "2026-08-27 17:35:40",
    severity: "CRITICAL",
    title: "CNC-01 Spindle Tool Wear & Thermal Runout",
    description: "AI anomaly confidence 82%. RUL countdown estimated at 42 cycles (100.8h). Lead time window: 65.5h.",
    failure_mode: "Spindle Tool Wear",
    sensor_trigger: "Triaxial Vibration Accelerometer (X-Axis)",
    trigger_value: "2.85 mm/s",
    threshold_value: "2.20 mm/s (Warn) / 3.80 mm/s (Crit)",
    lead_time_hours: 65.5,
    estimated_cost_usd: 38000.0,
    acknowledged: false,
    work_order_id: "WO-8920"
  },
  {
    id: "ALT-WRP01-1025",
    asset_id: "wrp-01",
    asset_name: "High-Speed Flow Packaging Wrapper",
    zone_id: "packaging",
    zone_name: "Packaging & Bottling Line",
    timestamp: "2026-08-27 17:20:10",
    severity: "WARNING",
    title: "WRP-01 Pneumatic Valve Leak & Pressure Loss",
    description: "AI anomaly confidence 72%. RUL countdown estimated at 95 cycles (228h). Lead time window: 148h.",
    failure_mode: "Pneumatic Valve Leak & Pressure Loss",
    sensor_trigger: "Ultrasound Acoustic Transducer",
    trigger_value: "48.0 dB",
    threshold_value: "45.0 dB (Warn) / 65.0 dB (Crit)",
    lead_time_hours: 148.0,
    estimated_cost_usd: 14500.0,
    acknowledged: true,
    acknowledged_by: "[SYS-ADMIN]"
  },
  {
    id: "ALT-ASRS01-1014",
    asset_id: "asrs-01",
    asset_name: "Automated High-Bay Stacker Crane 01",
    zone_id: "warehouse",
    zone_name: "Warehouse & Logistics (AS/RS)",
    timestamp: "2026-08-27 16:55:00",
    severity: "WARNING",
    title: "ASRS-01 Shaft Misalignment & Looseness",
    description: "AI anomaly confidence 74%. RUL countdown estimated at 110 cycles (264h). Lead time window: 171.6h.",
    failure_mode: "Shaft Misalignment & Looseness",
    sensor_trigger: "Triaxial Vibration Accelerometer (X-Axis)",
    trigger_value: "1.85 mm/s",
    threshold_value: "1.50 mm/s (Warn) / 3.00 mm/s (Crit)",
    lead_time_hours: 171.6,
    estimated_cost_usd: 18500.0,
    acknowledged: false
  }
];

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: "WO-8921",
    title: "CMP-01 Drive-End Bearing Vibration Diagnostic & Regreasing",
    asset_id: "cmp-01",
    asset_name: "Centrifugal Air Compressor 01 (250kW)",
    zone_id: "utilities",
    zone_name: "Utilities, Power & Plant HVAC",
    priority: "P1 - Emergency",
    status: "In Progress",
    created_at: "2026-08-27 08:30:00",
    assigned_to: "Dave Miller (Senior Millwright)",
    assigned_technician_role: "Level III Vibration Analyst",
    scheduled_start: "2026-08-27 15:00:00",
    estimated_hours: 3.5,
    actual_hours: 1.8,
    prescriptive_procedure: "1. Isolate 250kW motor feed. 2. Ultrasonic bearing scan. 3. Purge old grease and inject 40g Klüberquiet BQ 72-72. 4. Verify spectral harmonics at 1x/2x shaft rotational frequency.",
    required_parts: ["SKF Explorer 6314-2Z/C3 Deep Groove Bearing", "Klüberquiet BQ 72-72 Synthetic Grease"],
    parts_status: "Reserved",
    estimated_cost_usd: 1850.0,
    actual_cost_usd: 420.0,
    source_alert_id: "ALT-CMP01-1042",
    notes: ["Technician on site at compressor room.", "Pre-grease vibration RMS was 3.42 mm/s."]
  },
  {
    id: "WO-8920",
    title: "CNC-01 Spindle Taper Runout & Coolant Nozzle Alignment",
    asset_id: "cnc-01",
    asset_name: "5-Axis CNC Milling Center 01 (DMG Mori)",
    zone_id: "production",
    zone_name: "Production & Machining Lines",
    priority: "P2 - High",
    status: "Assigned",
    created_at: "2026-08-27 10:15:00",
    assigned_to: "Kenji Sato (CNC Specialist)",
    assigned_technician_role: "Precision Machine Tool Technician",
    scheduled_start: "2026-08-27 18:00:00",
    estimated_hours: 2.0,
    prescriptive_procedure: "1. Halt program execution. 2. Measure spindle drawbar retention force (>8.5 kN). 3. Clean ceramic hybrid bearing raceway. 4. Test run 5-axis calibration artifact.",
    required_parts: ["BT40 Tool Holder Pull Studs", "Spindle Coolant Nozzle Kit"],
    parts_status: "In Stock",
    estimated_cost_usd: 1200.0,
    source_alert_id: "ALT-CNC01-1038",
    notes: ["Scheduled for shift handover window."]
  },
  {
    id: "WO-8919",
    title: "WRP-01 Rotary Heat Sealing Bar Calrod Replacement",
    asset_id: "wrp-01",
    asset_name: "High-Speed Flow Packaging Wrapper",
    zone_id: "packaging",
    zone_name: "Packaging & Bottling Line",
    priority: "P3 - Medium",
    status: "Completed",
    created_at: "2026-08-26 14:00:00",
    assigned_to: "Carlos Mendez",
    assigned_technician_role: "Electrical Controls Technician",
    scheduled_start: "2026-08-26 16:00:00",
    estimated_hours: 2.5,
    actual_hours: 2.2,
    prescriptive_procedure: "1. LOTO seal bar supply. 2. Replace RTD thermocouple element. 3. Adjust PID loop deadband.",
    required_parts: ["PT100 3-Wire RTD Sensor Probe"],
    parts_status: "In Stock",
    estimated_cost_usd: 650.0,
    actual_cost_usd: 580.0,
    notes: ["Work completed successfully. Seal temperature stability restored to ±0.8°C."]
  }
];

export const MOCK_OVERVIEW: FactoryOverview = {
  timestamp: "2026-08-27 17:45:00",
  factory_name: "Apex Advanced Smart Manufacturing Facility (Plant 04)",
  plant_status: "Critical Attention",
  overall_oee: 89.2,
  overall_availability: 94.1,
  overall_performance: 97.4,
  overall_quality: 99.3,
  active_alerts_total: 4,
  critical_alerts_count: 2,
  warning_alerts_count: 2,
  critical_assets_count: 2,
  predicted_failures_7d: 4,
  predicted_failures_30d: 9,
  estimated_downtime_cost_avoided_usd: 184500.0,
  total_power_active_mw: 2.68,
  total_iot_sensors_online: 220,
  ai_monitoring_status: "Active – Continuous Quantile Inference on 18 Assets & 220 Sensors",
  top_risk_assets: [
    {
      id: "cmp-01",
      name: "Centrifugal Air Compressor 01 (250kW)",
      zone_id: "utilities",
      zone_name: "Utilities, Power & Plant HVAC",
      health_state: "Critical",
      health_index: 38.5,
      rul_cycles: 28,
      rul_hours: 67.2,
      failure_mode: "Bearing Outer Race Defect",
      risk_score: 73.8,
      cost_exposure_usd: 54000.0,
      lead_time_hours: 43.7
    },
    {
      id: "cnc-01",
      name: "5-Axis CNC Milling Center 01 (DMG Mori)",
      zone_id: "production",
      zone_name: "Production & Machining Lines",
      health_state: "Critical",
      health_index: 44.0,
      rul_cycles: 42,
      rul_hours: 100.8,
      failure_mode: "Spindle Tool Wear",
      risk_score: 67.2,
      cost_exposure_usd: 38000.0,
      lead_time_hours: 65.5
    },
    {
      id: "asrs-01",
      name: "Automated High-Bay Stacker Crane 01",
      zone_id: "warehouse",
      zone_name: "Warehouse & Logistics (AS/RS)",
      health_state: "Warning",
      health_index: 64.5,
      rul_cycles: 110,
      rul_hours: 264.0,
      failure_mode: "Shaft Misalignment & Looseness",
      risk_score: 42.6,
      cost_exposure_usd: 18500.0,
      lead_time_hours: 171.6
    },
    {
      id: "wrp-01",
      name: "High-Speed Flow Packaging Wrapper",
      zone_id: "packaging",
      zone_name: "Packaging & Bottling Line",
      health_state: "Warning",
      health_index: 68.0,
      rul_cycles: 95,
      rul_hours: 228.0,
      failure_mode: "Pneumatic Valve Leak & Pressure Loss",
      risk_score: 38.4,
      cost_exposure_usd: 14500.0,
      lead_time_hours: 148.0
    }
  ],
  zone_summaries: MOCK_ZONES,
  collective_sensor_health: {
    "vibration_sensors": { online: 48, warning: 4, critical: 2, health_pct: 94.2 },
    "thermal_rtd_sensors": { online: 64, warning: 2, critical: 1, health_pct: 96.8 },
    "motor_current_mcsa": { online: 32, warning: 2, critical: 1, health_pct: 98.1 },
    "ultrasonic_acoustic": { online: 24, warning: 3, critical: 1, health_pct: 92.5 },
    "pressure_hydraulic_pneumatic": { online: 36, warning: 1, critical: 0, health_pct: 97.4 },
    "oil_particle_dielectric": { online: 16, warning: 1, critical: 0, health_pct: 93.8 }
  }
};
